### ISSUE TITLE
Let users use same Path in different folders

### ISSUE THREAD

**Issue by TorleifHensvold** [emilte/music_library#7]
When creating a new wiki-page you must supply your own Path which gets added to the end of the URL. If the folder could be prepended then the same name for Path could be used in different folders with no problems.

E.g. Path of "witch" in folder "ex1" and "ex2" currently gives "Side med Path finnes allerede." as a message. If it could be made so that the same named page could get the …/ex1/witch and …/ex2/witch for the different folders, it would allow for more flexibility.

Another solution is to let the server create a new Path itself, and hide that from the user.

**Comment by emilte** [comment]
I removed this feature altogether. Currently too much work to implement dynamic url regex matching. Path is shown by id instead.
